server:
  port: 8084
regCenter:
  serverList: 192.168.0.200:2181
  namespace: yrw-transfer

#jobEventConfig:
#  url: jdbc:h2:mem:job_event_storage
#  driverClassName: org.h2.Driver
#  username: sa
#  password:

simpleJob:
  cron: 0/10 * * * * ?
  shardingTotalCount: 1

dataflowJob:
  cron: 0/20 * * * * ?
  shardingTotalCount: 2

#签到
signJob:
  id: signJob
  cron: 0 0 1 * * ?
  shardingTotalCount: 1
  description: 签到

#监控转让
monitorTransferJob:
  id: monitorTransferJob
  cron: 0/10 * * * * ?
  shardingTotalCount: 1
  description: 监控转让

spring:
  datasource:
    url: jdbc:mysql://192.168.0.51:3306/com.zwc?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

http:
    request:
        #从连接池中获取到连接的最长时间
        connectionRequestTimeout: 500
        #数据传输的最长时间
        connectTimeout: 2000
        #提交请求前测试连接是否可用
        socketTimeout: 10000
        #提交请求前测试连接是否可用
        staleConnectionCheckEnabled: true

    pool:
       #设置连接总数
       maxTotal: 200
       #设置每个地址的并发数
       defaultMaxPerRoute: 100