server:
  port: 8081
regCenter:
  serverList: 192.168.48.129:2181,192.168.48.131:2181,192.168.48.132:2181
  namespace: boot-elasticjob

#jobEventConfig:
#  url: jdbc:h2:mem:job_event_storage
#  driverClassName: org.h2.Driver
#  username: sa
#  password:

simpleJob:
  cron: 0/10 * * * * ?
  shardingTotalCount: 1

dataflowJob:
  cron: 0/20 * * * * ?
  shardingTotalCount: 2

spring:
  datasource:
    url: jdbc:mysql://192.168.0.51:3306/com.zwc?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root