regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite-springboot

zhengregCenter:
  serverList: localhost:2181
  namespace: root
  auth: auth

zhengmqregCenter:
  serverList: localhost:2181
  namespace: businessmq
  auth: auth

jobEventConfig:
  url: jdbc:h2:mem:job_event_storage
  driverClassName: org.h2.Driver
  username: sa
  password:

simpleJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou