server:
  port: 8910

eureka:
  client:
    serviceUrl:
          defaultZone: http://eurekaserver1:1111/eureka/,http://eurekaserver2:1111/eureka/,http://eurekaserver3:1111/eureka/

spring:
  application:
      name: customer-a