regCenter:
  serverList: 192.168.48.129:2181
  namespace: elastic-job-lite-springboot

jobEventConfig:
  url: jdbc:h2:mem:job_event_storage
  driverClassName: org.h2.Driver
  username: sa
  password:

simpleJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou

dataflowJob:
  cron: 0/20 * * * * ?
  shardingTotalCount: 2
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou