spring:
  application:
    name: compute-service

server:
  port: 2222

eureka:
  client:
    serviceUrl:
          defaultZone: http://eurekaserver1:1111/eureka/,http://eurekaserver2:1112/eureka/,http://eurekaserver3:1113/eureka/