# 默认的profile为slaveA，其他环境通过指定启动参数使用不同的profile，比如：
#   slaveB：java -jar my-spring-boot.jar --spring.profiles.active=slaveB
spring:
  profiles:
    active: slaveA
    server:
      #节点A端口
      slaveA:
        hostname: eurekaserver1
        port: 1111
      #节点B端口
      slaveB:
        hostname: eurekaserver2
        port: 1112
      #节点C端口
      slaveC:
        hostname: eurekaserver3
        port: 1113

---
spring:
  profiles: slaveA

server:
    #服务端口
    port: ${spring.profiles.server.slaveA.port}
eureka:
  instance:
    hostname: eurekaserver1
  client:
    register-with-eureka: false   #是否将eureka自身作为应用注册到eureka注册中心
    fetch-registry: false   #为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://${spring.profiles.server.slaveB.hostname}:${spring.profiles.server.slaveB.port}/eureka/,http://${spring.profiles.server.slaveC.hostname}:${spring.profiles.server.slaveC.port}/eureka/

---
spring:
  profiles: slaveB
server:
  #服务端口
  port: ${spring.profiles.server.slaveB.port}
eureka:
  instance:
    hostname: ${spring.profiles.server.slaveB.port}
  client:
    register-with-eureka: false   #是否将eureka自身作为应用注册到eureka注册中心
    fetch-registry: false   #为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://${spring.profiles.server.slaveA.hostname}:${spring.profiles.server.slaveA.port}/eureka/,http://${spring.profiles.server.slaveC.hostname}:${spring.profiles.server.slaveC.port}/eureka/


---
spring:
  profiles: slaveC
server:
  #服务端口
  port: ${spring.profiles.server.slaveC.port}
eureka:
  instance:
    hostname: ${spring.profiles.server.slaveC.port}
  client:
    register-with-eureka: false   #是否将eureka自身作为应用注册到eureka注册中心
    fetch-registry: false   #为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://${spring.profiles.server.slaveA.hostname}:${spring.profiles.server.slaveA.port}/eureka/,http://${spring.profiles.server.slaveB.hostname}:${spring.profiles.server.slaveB.port}/eureka/